#开箱部分（全局设置）
#开箱时长次数（变幻次数）
WingLongTime: 60
#每次变幻相差秒数
WingSpaceTime: 0.125

#九连开箱时长次数（变幻次数）
NineWingLongTime: 60
#九连每次变幻相差秒数
NineWingSpaceTime: 0.125

#如果想要自定义每个箱子的时间
#可以通过指令修改，顺序对应前：上、后：下
#当然，如果不启用开箱动画，设置了也不影响

#信息部分
#当玩家获得抽奖钥匙时，是否提示它？
KeyMessage: true

#音响
SoundSize: 1
#音色
SoundTimbre: 1

#自动变幻音色
ChangeSoundTimbre: false

#同步验证钥匙是否符合（通过匹配lore和名称的信息）（相当于添加了一个lore）
Lock: '&a此&c钥匙&a可以开启抽奖箱：&6 '

#是否启用日志功能
#启动后抽奖的结果将会在log.yml里显示
Log: true