name: CratesLottery
main: pers.tany.crateslottery.Main
version: 2.0.3
author: tany
depend: [ProtocolLib]
commands:
  crateslottery:
    usage: /crateslottery
    aliases: [cl]
permissions: 
  cl.lottery: 
    default: true
  cl.ninelottery: 
    default: true
  cl.allcrate: 
    default: true
  cl.checkall:
    default: true
  cl.break: 
    default: op
  cl.startall: 
    default: op
  cl.ninestartall: 
    default: op
  cl.showall: 
    default: op