name: CratesLottery
main: com.tany.crateslottery.Main
version: 2.0.1
author: tany
depend: [ProtocolLib,PlaceholderAPI]
commands:
  crateslottery:
    usage: /crateslottery
    aliases: [cl]
permissions: 
  cl.lottery: 
    default: true
  cl.ninelottery: 
    default: true
  cl.allcrate: 
    default: true
  cl.checkall:
    default: true
  cl.break: 
    default: op
  cl.startall: 
    default: op
  cl.ninestartall: 
    default: op
  cl.showall: 
    default: op